import {spawn} from 'node:child_process';import {chromium} from '@playwright/test';import {writeFile} from 'node:fs/promises';
const dir='reference-review/heso-calibration-2026-10-03',scenario=process.argv[2]??'left',port={left:5431,dense:5432,rush:5433}[scenario];
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(port),'--strictPort','--config','reference-review/tokyoghoul-w-live/vite-record.config.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,2500));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844},recordVideo:{dir,size:{width:390,height:844}}}),page=await context.newPage(),errors=[],samples=[];page.on('pageerror',e=>errors.push(String(e)));
if(scenario==='dense'){await page.goto(`http://127.0.0.1:${port}/${dir}/dense.html`);await page.waitForFunction(()=>window.denseBoard);}
else{await page.goto(`http://127.0.0.1:${port}/?review=session&scenario=${scenario}`);await page.locator('[data-unit="0"]').click();await page.locator('#playMachine').click();await page.waitForFunction(()=>globalThis.__session?.snapshot()?.intro?.phase==='complete');if(scenario==='left')await page.evaluate(()=>{__sessionReview.game().w.rng=()=>.9;});}
const start=Date.now(),limit=scenario==='rush'?240:scenario==='dense'?50:150;
for(let t=0;t<limit;t+=2){await page.waitForTimeout(2000);const sample=await page.evaluate(s=>s==='dense'?{snapshot:denseBoard.snapshot()}:{snapshot:__session.snapshot(),lastBonus:__sessionReview.game().lastBonus},scenario);samples.push({seconds:(Date.now()-start)/1000,...sample});if(scenario==='dense'&&t===18)await page.evaluate(()=>denseBoard.feed(false));if(scenario==='left'&&t===118){await page.locator('#controls-toggle').click();await page.locator('#feed-toggle').click();await page.locator('#controls-toggle').click();}if(scenario==='rush'&&sample.lastBonus?.payout===3000){await page.waitForTimeout(1500);break;}}
await page.screenshot({path:`${dir}/${scenario}-final-mobile.png`});await context.close();const file=await page.video().path();await writeFile(`${dir}/${scenario}-record.json`,JSON.stringify({file,errors,fixture:scenario==='rush'?'Initial RUSH and first result fixed; all shots natural, no ball placement.':scenario==='dense'?'Same production renderer/session, .05s requested launch cadence; all results miss. Natural launch for20sec then drain30sec; no physical ball placement.':'Natural .6s left launch at default .24 for120sec, then30sec drain. Results miss, no ball placement.',samples},null,2));console.log({file,errors,last:samples.at(-1)?.snapshot});
}finally{await browser?.close();server.kill();}
