import './style.css';
import {YozoraGame} from './model.js';
import {YozoraCabinet} from './cabinet.js';
const $=s=>document.querySelector(s),fmt=n=>n.toLocaleString('ja-JP');
const game=new YozoraGame();let cabinet,audio=null,sound=false,fast=false,pushUntil=0;
$('#app').innerHTML=`<main class="shell"><header><a href="/">← 銀玉クロニクル</a><span>NEW MACHINE / LOCAL PROTOTYPE</span></header><div class="layout"><section class="machine" aria-label="夜空 遊技台"><div class="counter"><div><small>大当り</small><b id="hits">0</b></div><div><small>総スタート</small><b id="starts">0</b></div><div><small>ST 残り</small><b id="st">—</b></div></div><div class="cabinet"><div class="engine" id="engine"></div><div class="crown">SAO<small>SWORD ART ONLINE · ALICIZATION</small></div><div class="demo-mark" id="demo"></div><section class="lcd" id="lcd" aria-label="液晶画面"><div class="sky"></div><div class="tower"></div><div class="lcd-title" id="mode">ALICIZATION</div><div class="scene-label" id="scene">セントラル・カセドラル</div><div class="reels" id="reels"><span class="reel">3</span><span class="reel">7</span><span class="reel">1</span></div><div class="cut" id="cut" hidden><strong id="headline"></strong><small id="caption"></small></div><div class="remaining" id="remaining"></div><div class="holds" id="holds" aria-label="保留0個">${'<i></i>'.repeat(4)}</div></section><span class="machine-label fair">FAIR START</span><span class="machine-label plus">PLUS START</span><span class="machine-label right">ATTACKER</span><button class="push" id="push" aria-label="演出PUSH">PUSH</button></div><div class="status" id="status" role="status">左打ちでスタート</div><div class="controls"><button class="primary" id="fire">遊技開始</button><button id="pause" disabled>一時停止</button><button id="supply">250玉補給</button></div><div class="balance"><span>持ち玉 <b id="stock">2,500</b></span><span>払出合計 <b id="total">0</b></span></div></section><aside class="info"><div class="eyebrow">PUBLIC SPECIFICATION STUDY · 5034</div><h1><small>e ソードアート・オンライン</small>アリシゼーション<em>夜空</em></h1><p>FAIR STARTから、剣が紡ぐ物語へ。<br>SWORD RUSH / War of Underworld</p><div class="specs"><span>通常時 大当り<strong>1 / 199.9</strong></span><span>右打ち 実質確率<strong>1 / 51.6</strong></span><span>SWORD RUSH<strong>53 回</strong></span><span>War of Underworld<strong>70 回</strong></span></div><p class="note">公開スペックに基づく非公式・制作途中の再現プロトタイプ。筐体、映像、音、玉経路は仮実装です。実機の完全再現版ではありません。</p><div class="tools"><button id="preview">演出を試す</button><button id="spec">再現範囲・仕様</button><button id="sound">試作音 OFF</button><button id="reset">遊技をリセット</button></div><p>発射は100発／分。発射停止後も盤面の玉・保留は消化します。一時停止ですべての進行が止まります。</p><p><a href="https://p-town.dmm.com/machines/5034" target="_blank" rel="noreferrer">参照：DMMぱちタウン 機種情報 ↗</a></p></aside></div></main><dialog id="dialog"></dialog>`;
try{cabinet=new YozoraCabinet($('#engine'));}catch(error){$('#engine').innerHTML='<p class="error">3D表示を開始できませんでした。WebGL対応ブラウザでページを再読み込みしてください。</p>';$('#fire').disabled=true;console.error(error);}
function tone(kind){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='win'?880:kind==='entry'?660:kind==='push'?220:440,audio.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='win'?1320:330,audio.currentTime+.15);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.21);}
function render(){const a=game.active,b=game.bonus,paused=game.paused;document.body.classList.toggle('paused',paused);
 $('#hits').textContent=game.jackpots;$('#starts').textContent=game.starts;$('#st').textContent=game.mode==='normal'||b?'—':game.remaining;$('#stock').textContent=fmt(game.stock);$('#total').textContent=fmt(game.total);
 $('#fire').textContent=game.phase==='ready'?'遊技開始':game.auto?'発射停止':'発射再開';$('#fire').disabled=paused;$('#pause').disabled=game.phase==='ready';$('#pause').textContent=paused?'再開':'一時停止';
 $('#demo').textContent=game.demo?'試演中 · 通常遊技の記録とは別':'映像・筐体は仮実装';
 $('#mode').textContent=game.mode==='normal'?'ALICIZATION':game.mode==='rush'?'SWORD RUSH':`WAR OF UNDERWORLD · ${['α','β','γ'][game.stage]}`;
 $('#scene').textContent=b?'BONUS':a?.reach?'Project Alicization':game.mode==='normal'?'セントラル・カセドラル':'右打ち';
 $('#remaining').textContent=game.mode==='normal'||b?'':`LAST ${String(game.remaining).padStart(2,'0')}`;
 $('#holds').setAttribute('aria-label',`保留${game.queue.length}個`);$('#holds').querySelectorAll('i').forEach((e,i)=>e.classList.toggle('on',i<game.queue.length));
 let title='',caption='';
 if(b){title=b.name==='BONUS'?'BONUS':b.name;caption=`${fmt(b.paid)} 玉 / ${fmt(b.rounds*150)} 玉　${Math.min(b.rounds,Math.floor(b.count/10)+1)}R`;
 }else if(a?.reach){const t=a.elapsed;
  if(t<2.5){title='REACH';caption='図柄テンパイ';}
  else if(t<5){title='Project Alicization';caption='公理教会へ';}
  else if(t<7){title='剣を、構えろ';caption='当落演出 · 仮映像';}
  else if(t<8.5){title='PUSH';caption=pushUntil>game.clock?'入力受付':'ボタンを押せ';}
  else{title='';caption='';}
 }
 $('#cut').hidden=!title;$('#headline').textContent=title;$('#caption').textContent=caption;$('#lcd').dataset.scene=b?'bonus':a?.reach?'reach':'normal';
 $('#push').disabled=!(a?.reach&&a.elapsed>=7&&a.elapsed<8.5&&!paused);
 const digits=[...game.lastDigits];if(a){for(let i=0;i<3;i++){const stopAt=a.reach?(i===1?9.2:1.5+i*.3):a.duration-.6+i*.2;digits[i]=a.elapsed<stopAt?1+Math.floor(a.elapsed*13+i*3)%9:(a.win||i!==1?a.digit:1+(a.digit+2)%9);}}
 $('#reels').querySelectorAll('span').forEach((e,i)=>e.textContent=digits[i]);
 $('#status').textContent=paused?'一時停止中':game.stock<=0?'玉がなくなりました · 250玉補給で続けられます':b?'右打ち · 大入賞口へ入賞中':game.mode!=='normal'?`右打ち · 残り${game.remaining}回`:`左打ち · 保留 ${game.queue.length} / 4`;
}
function modal(content){const alreadyPaused=game.paused;game.pause();audio?.suspend();render();const d=$('#dialog');d.innerHTML=content+'<button class="close" id="close">閉じる</button>';d.showModal();$('#close').onclick=()=>d.close();d.onclose=()=>{if(!alreadyPaused)game.resume();if(sound&&!game.paused)audio?.resume();render();};}
$('#fire').onclick=()=>{if(game.phase==='ready')game.start();else game.auto=!game.auto;if(sound)audio?.resume();render();};
$('#pause').onclick=()=>{if(game.paused){game.resume();if(sound)audio?.resume();}else{game.pause();audio?.suspend();}render();};
$('#supply').onclick=()=>{game.addStock();render();};$('#push').onclick=()=>game.push();
$('#sound').onclick=async()=>{sound=!sound;if(sound){audio??=new AudioContext();if(!game.paused)await audio.resume();}else await audio?.suspend();$('#sound').textContent=`試作音 ${sound?'ON':'OFF'}`;};
$('#reset').onclick=()=>{modal('<h2>遊技をリセット</h2><p>この台の持ち玉と遊技記録を初期状態に戻します。</p><button id="confirmReset">リセットする</button>');$('#confirmReset').onclick=()=>{game.reset();cabinet?.clear();fast=false;$('#dialog').close();render();};};
$('#spec').onclick=()=>modal(`<h2>再現範囲・仕様</h2><p>通常1/199.9、右打ち1/51.6。初当り：300玉・通常50%、300玉・ST53回48.5%、3000玉以上・ST70回1.5%。</p><p>ST53回中：1500玉・53回継続78%、1500玉・上位70回11%、3000玉以上・上位70回11%。上位中：1500玉60%、SWORD DRIVE40%。</p><p>SWORD DRIVE：1500/3000/4500/6000/7500玉が8.2/28.1/36.1/20.7/4.4%。9000玉が1.5%、7500玉＋再DRIVEが1%。公開された丸め値を利用しています。</p><p>賞球は大入賞口1入賞15玉、1R10カウント。表示は払い出しであり差玉ではありません。PUSHは演出操作で、抽選結果を変更しません。</p><h2>未再現・仮設定</h2><ul><li>実機キャラクター映像・音声・楽曲・全演出・カスタム・精密な筐体モデル</li><li>実機の釘・回転体の接触物理・電チュー／V入賞の時系列制御</li><li>保留4個・PLUS入賞率1.2%・玉経路・発射100発／分・演出秒数は仮設定</li><li>残保留・モードを跨ぐ保留制御・ラウンド間隔は簡略化。異なるモードへの移行時は保留をクリア</li></ul><p>5発に1発を6穴のFAIR STARTへ送り、2穴を入賞扱いとする論理モデルです。実機の回転体物理を再現したものではありません。</p>`);
$('#preview').onclick=()=>{modal(`<h2>演出を試す</h2><p>選択すると、この台の現在の遊技をリセットして試演します。当落を指定する制作確認用です。</p><div class="grid">${[['win','当りリーチ'],['miss','外れリーチ'],['bonus','初当り → ST'],['rush','SWORD RUSH'],['wou','War of Underworld'],['drive','SWORD DRIVE']].map(([id,label])=>`<button data-demo="${id}">${label}</button>`).join('')}</div><p><label><input id="fast" type="checkbox"> 試演を10倍速で確認</label></p>`);document.querySelectorAll('[data-demo]').forEach(el=>el.onclick=()=>{fast=$('#fast').checked;cabinet?.clear();game.demoScene(el.dataset.demo);$('#dialog').close();render();});};
function onVisibility(){if(document.hidden&&game.phase==='playing'){game.pause();audio?.suspend();render();}}
document.addEventListener('visibilitychange',onVisibility);
function frame(dt){if(!game.paused&&game.phase==='playing'){const steps=game.demo&&fast?10:1;for(let i=0;i<steps;i++){const delta=Math.max(0,Math.min(dt,.05));game.update(delta);cabinet.update(delta,game);for(const e of game.events.splice(0)){if(e.type==='shot')cabinet.spawn(e.shot);if(['entry','win','push','mode'].includes(e.type))tone(e.type);if(e.type==='push')pushUntil=game.clock+.7;}}}render();}
cabinet?.app.on('update',frame);window.__yozora={snapshot:()=>({...game.snapshot(),balls:cabinet?.balls.length||0,pixelRatio:cabinet?cabinet.view.canvas.width/cabinet.view.canvas.clientWidth:0})};
window.addEventListener('pagehide',()=>{cabinet?.app.off('update',frame);cabinet?.destroy();audio?.close();document.removeEventListener('visibilitychange',onVisibility);},{once:true});render();
