import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {Physics} from '../../src/physics.js';
const dir='reference-review/pixi-outlet';await mkdir(`${dir}/video`,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
try{const context=await browser.newContext({viewport:{width:1040,height:940},deviceScaleFactor:1,recordVideo:{dir:`${dir}/video`,size:{width:1040,height:940}}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://localhost:5173/outlet-pixi.html');await page.waitForFunction(()=>!!window.__outlet);await page.locator('#demo').click();
await page.waitForFunction(()=>{const s=window.__outlet.snapshot();return s.receipts.some(r=>Math.abs(r.x-210)<34&&s.time-r.time<.15);},{},{timeout:20000});await page.screenshot({path:`${dir}/entry.png`});
await page.waitForFunction(()=>window.__outlet.snapshot().time>15,{},{timeout:25000});await page.screenshot({path:`${dir}/flow.png`});
await page.waitForFunction(()=>window.__outlet.snapshot().time>35,{},{timeout:30000});await page.locator('#pause').click();const s=await page.evaluate(()=>window.__outlet.snapshot());await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>window.__outlet.snapshot()),s);const original=new Physics();assert.deepEqual(s.outlet,original.outlet);assert.deepEqual(s.colliders,original.colliders.filter(s=>s.role==='out-left'||s.role==='out-right'));assert.ok(s.counts.out>0);assert.equal(s.receipts.length,s.counts.out);assert.equal(new Set(s.receipts.map(r=>r.id)).size,s.receipts.length);assert.ok(s.receipts.some(r=>Math.abs(r.x-210)<34));assert.deepEqual(errors,[]);await page.locator('#guides').check();await page.screenshot({path:`${dir}/alignment.png`});await writeFile(`${dir}/verification.json`,JSON.stringify({snapshot:s,errors},null,2));const video=page.video();await context.close();await video.saveAs(`${dir}/outlet-demo.webm`);console.log(JSON.stringify({counts:s.counts,spawned:s.spawned,errors}));}finally{await browser.close();}
