import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,OffthreadVideo,Sequence,registerRoot,staticFile,useCurrentFrame} from 'remotion';
import timeline from './s5-timeline.json';import data from './s5-data.json';
const white='#edf5fc',muted='#a9bdcf',cyan='#91d4df',gold='#f0cf8a',font='"Hiragino Sans","Noto Sans JP",sans-serif';
const titles:any={intro:'配置を変え、同じ条件で比べる',attributes:'101本の基準と、変えない接触属性',constraints:'置けない地点は、理由を示して拒否',persistence:'保存・復元・読み戻しを、同じ配置へ',comparison:'入賞・無入賞区間・残球を比較',limitations:'改善と悪化を、条件ごとに見る',decision:'比較結果を見て、本編の採用を別に判断'};
const Card=({children,style={}}:any)=><div style={{background:'#142435',border:'1px solid #3c566b',borderRadius:15,padding:30,...style}}>{children}</div>;
function Operation({from,seconds,still}:any){const f=useCurrentFrame();const duration=Math.round(seconds*30);return <div style={{width:1152,height:690,position:'relative',overflow:'hidden',background:'#071019',borderRadius:12}}>{f<duration?<OffthreadVideo muted startFrom={Math.round(from*30)} endAt={Math.round((from+seconds)*30)} src={staticFile('operations.webm')} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:<Img src={staticFile(still)} style={{width:'100%',height:'100%',objectFit:'contain'}}/>}<div style={{position:'absolute',bottom:0,left:0,right:0,padding:'9px 18px',background:'#07111ff2',fontSize:23,color:muted}}>{f<duration?'実ツールの操作録画 · 音声なし':'実録画の静止を保持 · ループなし'} / V2 · 1440幅</div></div>}
function Notes({items}:any){return <Card style={{flex:1,height:690}}>{items.map(([title,text]:any)=><div key={title} style={{marginBottom:36}}><div style={{fontSize:31,color:cyan,fontWeight:750}}>{title}</div><p style={{fontSize:27,lineHeight:1.6,color:white,margin:'15px 0 0'}}>{text}</p></div>)}</Card>}
function OperateScene({id}:any){const opts:any={intro:{from:.5,seconds:1,still:'video-baseline.png',items:[['開発用ローカルツール','盤面全体の指定地点で配置を編集'],['基準は現行101本','本編への適用・自動探索は今回の対象外'],['操作＋図表で比較','保存した配置と実計測を対応づける']]},attributes:{from:1.95,seconds:1.55,still:'video-candidate.png',items:[['今回の候補','釘1：72.5, 488 → 70, 488'],['属性は維持','役割 michi / 半径 .2 / 反発 .85'],['所属群の許可地点','候補 grid:12:77 / 釘を増減しない']]},constraints:{from:3.8,seconds:1.5,still:'video-rejection.png',items:[['拒否の実例','固定部材の内部をクリック。候補配置を保持'],['共有する配置制約','禁止領域・固定部材・地点重複を検査'],['理由を表示','任意座標への自動配置ではありません']]},persistence:{from:5.7,seconds:4.6,still:'video-geometry-warning.png',items:[['保存 → 復元 → 読込','formatVersion 2で候補SHAを再現'],['定義と生成形状を分離','環境geometryの差は警告。現在制約の不正は拒否'],['識別して再検証','基準・候補・定義・環境SHAを記録']]}};const o=opts[id];return <div style={{display:'flex',gap:30,marginTop:30}}><Operation {...o}/><Notes items={o.items}/></div>}
function Results(){return <div style={{display:'flex',gap:28,marginTop:30}}><Card style={{width:1190,height:690}}><div style={{display:'flex',justifyContent:'space-between',fontSize:28}}><b style={{color:cyan}}>最終Chrome実測 · 基準 → 候補</b><span style={{color:muted}}>pin1 → grid:12:77</span></div><table style={{width:'100%',borderCollapse:'collapse',fontSize:25,marginTop:24}}><thead><tr>{['条件 / 位相','入賞数','無入賞最大秒','排出後残球'].map(x=><th key={x} style={{textAlign:'left',padding:'16px 5px',borderBottom:'1px solid #516b7b'}}>{x}</th>)}</tr></thead><tbody>{data.summary.map(x=><tr key={x.kind+x.phase}>{[`${x.kind==='mechanical'?'機械':'有限玉・外れ固定'} / ${x.phase}`,`${x.baselineEntries} → ${x.candidateEntries}`,`${x.baselineGap.toFixed(1)} → ${x.candidateGap.toFixed(1)}`,`${x.remaining[0]} → ${x.remaining[1]}`].map((v,i)=><td key={i} style={{padding:'12px 5px',borderBottom:'1px solid #314d60',fontVariantNumeric:'tabular-nums'}}>{v}</td>)}</tr>)}</tbody></table><p style={{fontSize:22,color:muted,lineHeight:1.5,margin:'16px 0 0'}}>入賞数：発射＋排出待ちの合計。無入賞：発射中の実観測窓。<br/>指定300秒発射＋45秒排出 / 強度.20 / 間隔.6秒 / dt1/120<br/>有限玉は実観測窓が約281〜300秒。計数・会計の整合を別途確認。</p></Card><Card style={{flex:1,height:690,padding:22}}><div style={{fontSize:26,color:cyan}}>流路の保存記録（基準）</div><Img src={staticFile('flow-baseline.svg')} style={{height:490,width:'100%',objectFit:'contain',marginTop:14}}/><div style={{fontSize:22,lineHeight:1.55,color:muted}}>実物理1秒ごとの記録再生<br/>12秒付近の静止図 / 補間なし</div></Card></div>}
function Limitations(){return <div style={{display:'flex',gap:30,marginTop:65}}><Card style={{flex:1,height:630}}><h2 style={{fontSize:36,color:cyan,margin:'0 0 40px'}}>条件によって、増加も減少もある</h2>{[['機械・位相.175','入賞 19 → 30 / 無入賞 70.2 → 39.3秒'],['機械・位相.35','入賞 28 → 25 / 無入賞 42.1 → 44.1秒'],['機械・位相0','入賞 27 → 29 / 無入賞 49.3 → 60.3秒']].map(([a,b])=><div key={a} style={{margin:'32px 0'}}><b style={{fontSize:28,color:gold}}>{a}</b><p style={{fontSize:27}}>{b}</p></div>)}<div style={{fontSize:23,color:muted}}>入賞数は排出待ちを含む / 今回の指定条件に限定</div></Card><Card style={{width:700,height:630}}><h2 style={{fontSize:36,margin:'0 0 40px'}}>確認した範囲と、限界</h2><div style={{fontSize:31,lineHeight:2.05}}>12条件の自然接触計測<br/>発射・処理済み・残球の整合<br/>実機・自然抽選の実績は未確認<br/>最適配置・改善率を保証しない</div><p style={{fontSize:25,color:muted,lineHeight:1.6,marginTop:35}}>geometry差を環境別に記録。<br/>本編への採用は別の判断です。</p></Card></div>}
function Decision(){return <><div style={{display:'flex',gap:24,alignItems:'center',marginTop:110}}>{[['現行本編','5台共通の固定配置を維持'],['ローカルツール','手動候補を保存・比較'],['採用判断','利点・悪化・未検証を確認']].map(([a,b],i)=><React.Fragment key={a}><Card style={{flex:1,height:260,textAlign:'center',padding:'55px 24px'}}><b style={{fontSize:40,color:cyan}}>{a}</b><p style={{fontSize:28,lineHeight:1.65}}>{b}</p></Card>{i<2&&<span style={{fontSize:45,color:muted}}>→</span>}</React.Fragment>)}</div><Card style={{marginTop:45,padding:28}}><div style={{fontSize:35}}>ローカル500テスト・既存遊技UI・V2ツール12条件の検証が成功</div><p style={{fontSize:26,color:muted,margin:'24px 0 0'}}>今回の成果：手動比較ツール / 本番反映・新しい網羅探索は含めません</p></Card></>}
function Movie(){const frame=useCurrentFrame();let clip=timeline.clips[0];for(const c of timeline.clips)if(frame>=c.start_frame)clip=c;const subtitle=frame<clip.start_frame+clip.duration_frames?clip.text:'';return <AbsoluteFill style={{background:'#08131f',color:white,fontFamily:font,padding:'32px 64px'}}><div style={{fontSize:25,color:muted,letterSpacing:1.3}}>SILVERBALL CHRONICLES / SPRINT 5 / ISSUE #22</div><h1 style={{fontSize:48,margin:'20px 0 0'}}>{titles[clip.id]}</h1><Sequence from={clip.start_frame} durationInFrames={(timeline.clips[timeline.clips.indexOf(clip)+1]?.start_frame??timeline.total_duration_frames+60)-clip.start_frame} layout="none">{['intro','attributes','constraints','persistence'].includes(clip.id)?<OperateScene id={clip.id}/>:clip.id==='comparison'?<Results/>:clip.id==='limitations'?<Limitations/>:<Decision/>}</Sequence><div style={{position:'absolute',bottom:61,left:64,right:64,minHeight:114,padding:'13px 22px',borderRadius:10,textAlign:'center',fontSize:32,lineHeight:1.6,background:subtitle?'#040b13f5':'transparent'}}>{subtitle.split('。').filter(Boolean).map((part,i)=><span key={i} style={{display:'block'}}>{part}。</span>)}</div><div style={{position:'absolute',bottom:22,left:64,fontSize:22,color:muted}}>ナレーション：VOICEVOX:ずんだもん（ノーマル）</div><div style={{position:'absolute',bottom:22,right:64,fontSize:22,color:muted}}>V2 / 最終ローカル検証 / 本編の配置採用は別判断</div>{timeline.clips.map(c=><Sequence key={c.id} from={c.start_frame} durationInFrames={c.duration_frames} layout="none"><Audio src={staticFile(c.audio_file)}/></Sequence>)}</AbsoluteFill>}
registerRoot(()=> <Composition id="S5Review" component={Movie} width={1920} height={1080} fps={30} durationInFrames={timeline.total_duration_frames+60}/>);
