import React from 'react';
import {AbsoluteFill,Composition,Img,OffthreadVideo,Sequence,registerRoot,staticFile} from 'remotion';
const font='"Hiragino Sans","Noto Sans JP",sans-serif',bg='#08131f',white='#edf5fc',muted='#adc1d1';
function Banner({children}:any){return <div style={{position:'absolute',left:48,right:48,top:25,fontSize:35,color:white,fontWeight:700}}>{children}</div>}
function Before(){return <AbsoluteFill style={{background:bg,color:white,fontFamily:font}}><Banner>変更前：計測が終わってから、時刻を選んで見る</Banner><div style={{position:'absolute',left:48,top:110,width:1220,height:825,overflow:'hidden',border:'1px solid #506b7e',borderRadius:10}}><Img src={staticFile('before-recorded-ui.png')} style={{width:1220,position:'absolute',left:0,bottom:0}}/></div><div style={{position:'absolute',left:1320,top:210,right:45,fontSize:35,lineHeight:1.8}}>実物理1秒ごとの保存記録<br/><br/>スライダーで指定した時刻の静止表示<br/><br/>連続する玉の動きはまだ見られない</div><div style={{position:'absolute',bottom:32,left:48,fontSize:24,color:muted}}>変更前の実画面 / 先行ローカル検証の12秒フレーム / 現在のLive映像ではありません</div></AbsoluteFill>}
function Live({mobile=false}:any){return <AbsoluteFill style={{background:bg,color:white,fontFamily:font}}><Banner>{mobile?'390幅でも、盤面と操作・計数を一緒に見る':'変更後：編集した盤面で、玉が連続して流れる'}</Banner><div style={{position:'absolute',left:48,top:105,width:mobile?450:1460,height:912,overflow:'hidden'}}><OffthreadVideo muted src={staticFile(mobile?'live-390.mp4':'live-1440.mp4')} style={{width:'100%',height:'100%',objectFit:'contain'}}/></div><div style={{position:'absolute',left:mobile?590:1540,top:mobile?250:180,right:40,fontSize:mobile?37:28,lineHeight:1.75}}>{mobile?<><b>発射・停止・休止を盤面の近くに</b><p>発射／ヘソ／その他入賞／残球／排出／返却を確認</p><p>本編の釘配置・抽選・賞球は変更しない</p></>:<><b>実操作を等速で収録</b><p>発射停止後も残球は流れる</p><p>休止・再開</p><p>リセット後は1クリックで発射</p></>}</div><div style={{position:'absolute',bottom:14,left:48,fontSize:21,color:muted}}>追加収録 / pin1 → grid:12:77 / 1440×900・390×844は独立試射 / 実操作・等速 / 25fps収録→30fps編集（補間なし）</div></AbsoluteFill>}
function Reference(){return <AbsoluteFill><OffthreadVideo src={staticFile('approved-reference.mp4')} style={{width:'100%',height:'100%'}}/><div style={{position:'absolute',top:0,left:0,right:0,height:76,boxSizing:'border-box',padding:'9px 45px',fontFamily:font,fontSize:23,color:white,background:'#08131f'}}>追補前に作成した説明映像 / 表は先行実測・比較物理source164は同一 / 承認済み7文・音声を保持</div></AbsoluteFill>}
function Movie(){return <AbsoluteFill><Sequence from={0} durationInFrames={90}><Before/></Sequence><Sequence from={90} durationInFrames={660}><Live/></Sequence><Sequence from={750} durationInFrames={180}><Live mobile/></Sequence><Sequence from={930} durationInFrames={1921}><Reference/></Sequence></AbsoluteFill>}
registerRoot(()=> <Composition id="S5LiveReview" component={Movie} width={1920} height={1080} fps={30} durationInFrames={2851}/>);
