import test from 'node:test';import assert from 'node:assert/strict';
import {createBoardFlow} from '../src/pixi/board-flow.js';
import {measureUnit} from '../tools/qa05-measurement.mjs';
import {createBaselineLayout,applyMove,resolvePins} from '../src/dev/pin-layout-model.js';
import {measureLayout,compareLayouts} from '../src/dev/pin-layout-measurement.js';
test('baseline factory measurement matches established qa05 raw events/counts/accounting',()=>{const b=createBaselineLayout();for(const kind of ['mechanical','finite-stock-fixed-loss']){const old=measureUnit({pegSeed:101,phase:.175,kind,seconds:12,drain:3}),now=measureLayout(b,{phase:.175,kind,seconds:12,drain:3});for(const key of ['events','physical','ledger','session','atStop','end'])if(key==='physical'){for(const field of Object.keys(old[key]))assert.deepEqual(now[key][field],old[key][field]);}else assert.deepEqual(now[key],old[key],key);assert.ok(now.physical.countsMatchOutcomes);assert.deepEqual(now.pins,resolvePins(b));}});
test('paired comparison preserves fixed shapes/conditions and exposes short-window scope',async()=>{const b=createBaselineLayout(),c=applyMove(b,1,'grid:12:77'),r=await compareLayouts(c,{seconds:2,drain:1});assert.equal(r.comparable,true);assert.equal(r.fullWindow,false);assert.equal(r.codeSHA,null);assert.equal(r.codeSHAProvided,false);assert.notEqual(r.baseline.layoutHash,r.candidate.layoutHash);assert.equal(r.baseline.runs.length,6);assert.equal(r.candidate.runs.length,6);for(let i=0;i<6;i++){const a=r.baseline.runs[i],b=r.candidate.runs[i];assert.deepEqual(a.fixed,b.fixed);assert.equal(a.fixedHash,b.fixedHash);assert.deepEqual(a.conditions,b.conditions);assert.ok(b.physical.reconciled);assert.ok(b.frames.length);assert.ok(b.observation.observedPhysicsFiringSeconds<=2);}});
test('invalid candidates/unsupported conditions fail before trial and failure is not skipped',async()=>{const b=createBaselineLayout();for(const options of [{phase:.1},{kind:'natural-win'},{seconds:NaN},{drain:-1},{seconds:301}])assert.throws(()=>measureLayout(b,options));const bad=structuredClone(b);bad.placements[0].siteId='free:70:488';await assert.rejects(compareLayouts(bad));assert.throws(()=>measureLayout(b,{seconds:1,onProgress:()=>{throw new Error('stop');}}),/stop/);});

test('moving windmill execution state cannot mutate initial fixed-condition snapshot',()=>{const r=measureLayout(createBaselineLayout(),{seconds:12,drain:3});assert.deepEqual(r.fixed.mechanisms,createBoardFlow({lcd:true}).flow.physics.mechanisms);assert.ok(r.mechanismEndState.some((m,i)=>m.angle!==r.fixed.mechanisms[i].angle||m.omega!==r.fixed.mechanisms[i].omega),'natural contacts advance windmill while initial condition remains unchanged');});
