import test from 'node:test';import assert from 'node:assert/strict';
import {createBoardFlow} from '../src/pixi/board-flow.js';
import {createBaselineLayout,getPinLayoutModel,resolvePins,validateLayout,validateMove,applyMove,diffLayout,serializeLayout,parseLayout,layoutHash,exportLayout,importLayout,inspectImport,constraintHash,constraintDefinition,engineGeometryHash} from '../src/dev/pin-layout-model.js';
test('exact baseline101 contacts match production and all six groups have intended population',()=>{const m=getPinLayoutModel(),b=createBaselineLayout();assert.deepEqual(resolvePins(b),createBoardFlow({lcd:true}).flow.physics.pins);assert.deepEqual(m.groups.map(g=>m.pins.filter(p=>p.group===g.id).length),[26,10,55,2,3,5]);assert.equal(m.pins.length,101);assert.equal(validateLayout(b).valid,true);for(const g of m.groups)if(g.editable)assert.ok(m.sites.some(s=>s.id.startsWith('grid:')&&s.allowedGroups.includes(g.id)));assert.deepEqual(parseLayout(serializeLayout(b)),b);});
test('move preserves stable role/r/restitution and only requested coordinate changes',()=>{const b=createBaselineLayout(),c=applyMove(b,1,'grid:12:77'),old=resolvePins(b),next=resolvePins(c);assert.deepEqual(diffLayout(c).map(p=>p.pinId),[1]);assert.deepEqual(next.slice(1),old.slice(1));assert.deepEqual({...next[0],x:old[0].x,y:old[0].y},old[0]);assert.deepEqual([next[0].x,next[0].y],[70,488]);assert.deepEqual(resolvePins(b),old);});
test('all edited groups have at least one legal move and fixed heso rejects move',()=>{const m=getPinLayoutModel(),b=createBaselineLayout();for(const g of m.groups.filter(g=>g.editable)){const pin=m.pins.find(p=>p.group===g.id);assert.ok(m.sites.some(s=>s.allowedGroups.includes(g.id)&&s.id.startsWith('grid:')&&validateMove(b,pin.id,s.id).valid),g.id);}assert.equal(validateMove(b,91,'grid:12:77').valid,false);});
test('rejects unknown/outside/fixed polygon sites, foreign baseline, duplicate/count and arbitrary attributes',()=>{const b=createBaselineLayout();for(const site of ['grid:999:0','grid:50:50','baseline:2'])assert.equal(validateMove(b,1,site).valid,false);for(const mutate of [c=>c.placements.pop(),c=>c.placements[1].pinId=1,c=>c.placements[1].siteId=c.placements[0].siteId,c=>c.placements[0].x=999,c=>c.constraintVersion='other',c=>c.baselineIdentity='other',c=>c.extra={}]){const c=structuredClone(b);mutate(c);assert.equal(validateLayout(c).valid,false);assert.throws(()=>resolvePins(c));}assert.throws(()=>parseLayout('null'));assert.throws(()=>parseLayout('{invalid'));});
test('moved pin proximity is checked against unchanged original pins',()=>{const b=createBaselineLayout();assert.equal(validateMove(b,1,'grid:14:78').valid,false);assert.ok(validateMove(b,1,'grid:14:78').errors.some(e=>e.code==='clearance'));});
test('saved export verifies true SHA, reorders canonical placements, and rejects tampering',async()=>{const b=createBaselineLayout(),c=applyMove(b,1,'grid:12:77'),saved=await exportLayout(c),v=JSON.parse(saved);assert.match(v.metadata.baselineSHA,/^[a-f0-9]{64}$/);assert.equal(v.metadata.layoutSHA,await layoutHash(c));assert.equal(v.metadata.constraintSHA,await constraintHash());assert.deepEqual(await importLayout(saved),c);v.metadata.layoutSHA='0'.repeat(64);await assert.rejects(importLayout(JSON.stringify(v)));v.metadata.layoutSHA=await layoutHash(c);v.layout.placements[0].siteId='grid:12:78';await assert.rejects(importLayout(JSON.stringify(v)));const reversed=structuredClone(c);reversed.placements.reverse();assert.equal(await layoutHash(reversed),await layoutHash(c));assert.deepEqual(await importLayout(await exportLayout(b)),b);});

// The definition is checked against the production generators, not rounded output.
test('declared rail/transform inputs reproduce installed production geometry',async()=>{
 const {OUTER_ARC,INNER_ARC,LAUNCH_RAIL_RADIUS}=await import('../src/pixi/board-rails.js');const {sourcePoint}=await import('../src/pixi/source-layout.js');const d=constraintDefinition(),g=d.boardRailGeneration;
 const build=(r,n,end)=>Array.from({length:n+1},(_,i)=>{const a=Math.PI+(end-Math.PI)*i/n;const [x,y]=sourcePoint([g.center[0]+r[0]*Math.cos(a),g.center[1]+r[1]*Math.sin(a)]);return {x,y};});
 assert.deepEqual(build(g.outerRadii,g.outerSegments,Math.PI*2),OUTER_ARC);assert.deepEqual(build(g.innerRadii,g.innerSegments,Math.PI*g.exitAnglePiMultiplier),INNER_ARC);assert.equal(g.railRadius,LAUNCH_RAIL_RADIUS);
 const t=d.sourceTransform;for(const xy of [[72,120],[0,0],[444,530],[814,940]])assert.deepEqual(xy.map((v,i)=>t.boardOrigin[i]+(v-t.sourceOrigin[i])*t.scale),sourcePoint(xy));
 assert.ok(!('fixed' in d));assert.ok(!('sites' in d));assert.ok(d.sourceCoordinates.UNIT_SOURCE.length>0);
});
test('foreign exact engine geometry warns while rule/layout mismatch and old schema reject',async()=>{
 const b=applyMove(createBaselineLayout(),1,'grid:12:77'),v=JSON.parse(await exportLayout(b));assert.equal(v.formatVersion,2);assert.equal(v.metadata.engineGeometrySHA,await engineGeometryHash());v.metadata.engineGeometrySHA='a'.repeat(64);
 const imported=await inspectImport(JSON.stringify(v));assert.deepEqual(imported.layout,b);assert.equal(imported.geometryMismatch,true);assert.match(imported.warning,/環境別/);assert.equal(imported.recordedEngineGeometrySHA,'a'.repeat(64));assert.deepEqual(await importLayout(JSON.stringify(v)),b);
 v.metadata.constraintSHA='b'.repeat(64);await assert.rejects(importLayout(JSON.stringify(v)),/constraint/);v.metadata.constraintSHA=await constraintHash();v.metadata.engineGeometrySHA='invalid';await assert.rejects(importLayout(JSON.stringify(v)),/metadata/);
 delete v.formatVersion;await assert.rejects(importLayout(JSON.stringify(v)),/再保存/);
});
