import test from 'node:test';import assert from 'node:assert/strict';
import {createLiveTrial}from '../src/dev/pin-layout-live.js';
import {createBaselineLayout,applyMove,resolvePins,layoutHash}from '../src/dev/pin-layout-model.js';
import {createBoardFlow}from '../src/pixi/board-flow.js';
function frames(live,from,to,ms=40){for(let t=from+ms;t<=to;t+=ms)live.advance(t);}
test('live uses the same factory pins and fixed steps as the established mechanical solver',async()=>{const layout=applyMove(createBaselineLayout(),1,'grid:12:77'),live=await createLiveTrial(layout),ref=createBoardFlow({lcd:true,normalPower:.20,launchInterval:.6});ref.flow.physics.pins=resolvePins(layout);ref.setMode('normal');ref.flow.start();live.start();live.advance(0);frames(live,0,1000);for(let i=0;i<120;i++)ref.flow.step(1/120);assert.deepEqual(live.renderState().pins,ref.flow.physics.pins);assert.deepEqual(live.renderState().balls,ref.flow.physics.balls);assert.deepEqual(live.snapshot().counts,ref.flow.counts);assert.equal(live.snapshot().layoutHash,await layoutHash(layout));assert.ok(live.snapshot().reconciled);assert.ok(Math.abs(live.snapshot().physicalTime-1)<1e-10);});
test('stop leaves existing balls progressing without new shots, pause freezes and resume discards wall gap',async()=>{const live=await createLiveTrial(createBaselineLayout());live.start();live.advance(0);frames(live,0,1000);live.stop();const stopped=live.snapshot();assert.ok(stopped.inFlight>0);frames(live,1000,1200);assert.equal(live.snapshot().shots,stopped.shots);assert.ok(live.snapshot().physicalTime>stopped.physicalTime);assert.notDeepEqual(live.snapshot().balls,stopped.balls);live.pause('hidden');assert.equal(live.snapshot().pauseReason,'hidden');const paused=live.snapshot();live.advance(999000);assert.deepEqual(live.snapshot().balls,paused.balls);assert.equal(live.snapshot().physicalTime,paused.physicalTime);live.resume();live.advance(1000000);assert.equal(live.snapshot().physicalTime,paused.physicalTime);live.advance(1000040);assert.ok(Math.abs(live.snapshot().physicalTime-paused.physicalTime-4/120)<1e-10);assert.equal(live.snapshot().feeding,false);assert.equal(live.snapshot().pauseReason,'');});
test('bounded late frame exposes dropped wall time, with no unlimited catch-up',async()=>{const live=await createLiveTrial(createBaselineLayout());live.start();live.advance(0);assert.equal(live.advance(1000),6);let s=live.snapshot();assert.ok(Math.abs(s.physicalTime-.05)<1e-10);assert.equal(s.wallActiveSeconds,1);assert.equal(s.droppedWallSeconds,.95);const beforeFailure=live.snapshot();assert.throws(()=>live.advance(900),/backwards/);assert.deepEqual(live.snapshot(),beforeFailure);assert.throws(()=>live.advance(NaN),/Invalid/);assert.deepEqual(live.snapshot(),beforeFailure);});
test('reset swaps validated layout/hash and clears time/count/balls, invalid reset preserves old trial',async()=>{const live=await createLiveTrial(createBaselineLayout());live.start();live.advance(0);frames(live,0,1000);const old=live.snapshot();const invalid=createBaselineLayout();invalid.placements[0].siteId='free:70:488';await assert.rejects(live.reset(invalid));assert.equal(live.snapshot().layoutHash,old.layoutHash);assert.equal(live.snapshot().shots,old.shots);const candidate=applyMove(createBaselineLayout(),1,'grid:12:77');await live.reset(candidate);const s=live.snapshot();assert.equal(s.layoutHash,await layoutHash(candidate));assert.equal(s.shots,0);assert.equal(s.inFlight,0);assert.equal(s.physicalTime,0);assert.equal(s.paused,true);assert.equal(s.feeding,false);assert.deepEqual(live.renderState().pins,resolvePins(candidate));});
test('concurrent reset takes only the latest layout and dispose prevents late resets and advancement',async()=>{const live=await createLiveTrial(createBaselineLayout()),candidate=applyMove(createBaselineLayout(),1,'grid:12:77');const a=live.reset(candidate),b=live.reset(createBaselineLayout());assert.equal(await a,false);assert.equal(await b,true);assert.equal(live.snapshot().layoutHash,await layoutHash(createBaselineLayout()));live.start();live.advance(0);live.advance(40);const reset=live.reset(candidate);live.dispose();assert.equal(await reset,false);const s=live.snapshot();assert.equal(live.advance(100000),0);assert.equal(live.start(),false);assert.equal(live.resume(),false);assert.equal(await live.reset(candidate),false);assert.equal(live.snapshot().physicalTime,s.physicalTime);assert.equal(live.snapshot().disposed,true);});
