import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {browserLaunchOptions} from './browser-launch.js';
import {validatePR,validateCD,parseReleaseSummary,releaseNotes,executeCD,verifyCurrentDeployment,verifyPublicAssets,publishGitHubRelease,assetDigest} from '../tools/release-cd.js';
const sha='a'.repeat(40),other='c'.repeat(40),repo='sintaro-katuta/silverball-chronicles',version='0.1.0',uuid='79011609-06b2-4c3b-8ca4-2e4689a27c15';
const summary={version,sprints:[1,2,3],issues:[2,3,4,10,11],improvements:['通常とRUSHの消化回数を区別できます。'],fixes:['スマホ結果の改行を修正。'],knownLimitations:['スマホ実機と音の実聴取は未検証。']};
const body='PM accepted scope\n```json\n'+JSON.stringify({silverballReleaseSummary:summary})+'\n```';
function event(){return {action:'closed',repository:{full_name:repo},pull_request:{number:12,merged:true,base:{ref:'main'},head:{ref:'release/'+version,repo:{full_name:repo}},merge_commit_sha:sha,body}};}
function inputs(){return {enabled:'true',event:event(),repository:repo,checkoutSHA:sha,packageVersion:version,mainSHA:sha};}
const candidate={candidateId:uuid,git:{commit:sha,dirty:false},source:{sha256:'b'.repeat(64)},assets:[{path:'index.html',size:5,sha256:createHash('sha256').update('hello').digest('hex')}]};
function setup(){const calls=[],states=[];let context=validateCD(inputs());const deps={prepare:async()=>{calls.push('prepare');return structuredClone(candidate);},deploy:async()=>{calls.push('deploy');return uuid;},verifyPublic:async()=>{calls.push('verify-public');return {deploymentId:uuid};},smoke:async()=>{calls.push('smoke');},saveCheckpoint:async r=>{calls.push('checkpoint:'+r.status);states.push(structuredClone(r));},createRelease:async()=>{calls.push('create-release');return 'https://github.com/'+repo+'/releases/tag/'+version;},refreshMain:async()=>sha,getCurrentDeployment:async()=>({id:uuid,createdOn:'2026-10-01T00:00:00Z',versions:[{version_id:uuid,percentage:100}]}),generateNotes:async()=> 'Merged PR #12',now:()=> '2026-10-07T00:00:00Z'};return {context,deps,calls,states};}
test('managed Chromium avoids local Chrome dependency without broad legacy changes',()=>{assert.equal(browserLaunchOptions({}).channel,'chrome');assert.equal(browserLaunchOptions({PLAYWRIGHT_BROWSER:'chromium'}).channel,undefined);assert.throws(()=>browserLaunchOptions({PLAYWRIGHT_BROWSER:'unknown'}));});
test('PR paths and structured three-Sprint summary are required',()=>{assert.equal(validatePR(event()).kind,'release');const e=event();e.pull_request.head.ref='sprint/S01';e.pull_request.base.ref='release/'+version;assert.equal(validatePR(e).kind,'sprint');e.pull_request.head.ref='sprint/';assert.throws(()=>validatePR(e));assert.throws(()=>parseReleaseSummary('none',version));for(const value of [{...summary,sprints:[1,1,2]},{...summary,issues:[2,2]},{...summary,version:'1.0.0'}])assert.throws(()=>parseReleaseSummary('```json\n'+JSON.stringify({silverballReleaseSummary:value})+'\n```',version));});
for(const kind of ['disabled','push','not-merged','wrong-base','fork','wrong-repo','wrong-head','wrong-package','wrong-checkout','stale-main','wrong-tag','newer-release'])test(`CD refuses ${kind} before operations`,()=>{const i=inputs();if(kind==='disabled')i.enabled=undefined;if(kind==='push')i.eventName='push';if(kind==='not-merged')i.event.pull_request.merged=false;if(kind==='wrong-base')i.event.pull_request.base.ref='release/'+version;if(kind==='fork')i.event.pull_request.head.repo.full_name='foreign/repo';if(kind==='wrong-repo')i.repository='foreign/repo';if(kind==='wrong-head')i.event.pull_request.head.ref='sprint/S03';if(kind==='wrong-package')i.packageVersion='1.0.0';if(kind==='wrong-checkout')i.checkoutSHA=other;if(kind==='stale-main')i.mainSHA=other;if(kind==='wrong-tag')i.tagSHA=other;if(kind==='newer-release')i.latestRelease={tag_name:'0.2.0'};assert.throws(()=>validateCD(i));});
test('normal CD publishes only after deployment, fresh public validation and smoke',async()=>{const s=setup();const result=await executeCD(s.context,s.deps);assert.equal(result.status,'released');assert.deepEqual(s.calls,['prepare','checkpoint:pre-deploy','deploy','checkpoint:deployed','verify-public','smoke','checkpoint:smoke-verified','create-release']);assert.equal(s.states[0].status,'pre-deploy');assert.ok(s.states[0].previousDeployment);assert.equal(s.states[1].status,'deployed');assert.equal(s.states[2].status,'smoke-verified');});
for(const phase of ['prepare','deploy','verifyPublic','smoke','createRelease'])test(`CD ${phase} failure is not a successful Release`,async()=>{const s=setup();s.deps[phase]=async()=>{throw new Error('fixture '+phase);};await assert.rejects(executeCD(s.context,s.deps));if(phase!=='createRelease')assert.ok(!s.calls.includes('create-release'));if(['verifyPublic','smoke','createRelease'].includes(phase))assert.ok(s.states.length);});
test('a moved main or dirty candidate cannot publish',async()=>{for(const variant of ['main','dirty']){const s=setup();if(variant==='main')s.deps.refreshMain=async()=>other;else s.deps.prepare=async()=>({...candidate,git:{commit:sha,dirty:true}});await assert.rejects(executeCD(s.context,s.deps));assert.ok(!s.calls.includes('deploy'));}});
test('same version/SHA successful rerun is a no-op; draft retry still checks public deployment',async()=>{const first=setup();await executeCD(first.context,first.deps);const record=first.states.at(-1),i=inputs();i.tagSHA=sha;i.release={tag_name:version,draft:false,body:'<!-- silverball-release:'+JSON.stringify(record)+' -->'};const c=validateCD(i);const again=setup();again.context=c;await executeCD(c,again.deps);assert.deepEqual(again.calls,[]);
 i.release.draft=true;const retry=setup();retry.context=validateCD(i);retry.deps.checkpoint=record;await executeCD(retry.context,retry.deps);assert.ok(!retry.calls.includes('deploy'));assert.ok(retry.calls.includes('verify-public'));assert.ok(retry.calls.includes('smoke'));assert.ok(retry.calls.includes('create-release'));
 i.tagSHA=other;assert.throws(()=>validateCD(i));});
test('smoke failed checkpoint resumes without redeploy, and altered checkpoint cannot resume',async()=>{const first=setup();first.deps.smoke=async()=>{throw new Error('smoke');};await assert.rejects(executeCD(first.context,first.deps));const retry=setup();retry.deps.checkpoint=first.states.find(s=>s.status==='deployed');await executeCD(retry.context,retry.deps);assert.ok(!retry.calls.includes('deploy'));assert.ok(retry.calls.includes('verify-public'));for(const change of [{sha:other},{assetDigest:'bad'},{worker:'wrong'},{cloudflareVersionId:'bad'}]){const bad=setup();bad.deps.checkpoint={...first.states.find(s=>s.status==='deployed'),...change};await assert.rejects(executeCD(bad.context,bad.deps));assert.ok(!bad.calls.includes('create-release'));}});
test('fresh traffic must be exactly the recorded Worker Version at 100%',()=>{const data={success:true,result:{deployments:[{id:uuid,versions:[{version_id:uuid,percentage:100}]}]}};assert.equal(verifyCurrentDeployment(data,{cloudflareVersionId:uuid}).deploymentId,uuid);for(const versions of [[{version_id:'wrong',percentage:100}],[{version_id:uuid,percentage:50},{version_id:'other',percentage:50}]])assert.throws(()=>verifyCurrentDeployment({success:true,result:{deployments:[{versions}]}},{cloudflareVersionId:uuid}));});
test('public SHA verification excludes only provider config and detects same-size bytes',async()=>{const m={...candidate,assets:[...candidate.assets,{path:'_headers',size:0,sha256:'x'}]},calls=[];const response=text=>({ok:true,arrayBuffer:async()=>Buffer.from(text)});const value=await verifyPublicAssets(m,{fetcher:async url=>{calls.push(String(url));return response('hello');},retries:1});assert.equal(value.filesChecked,1);assert.ok(!calls.some(p=>p.includes('_headers')));await assert.rejects(verifyPublicAssets(m,{fetcher:async()=>response('HELLO'),retries:1}),/mismatch/);});
test('notes show three accepted Sprints and limits, and never call deployed-only state successful',async t=>{const s=setup();await executeCD(s.context,s.deps);const candidateNotes=releaseNotes(s.context,'generated');assert.match(candidateNotes,/公開候補/);assert.doesNotMatch(candidateNotes,/公開日/);const notes=releaseNotes(s.context,'Merged release PR',s.states.at(-1));assert.match(notes,/対象Sprint：1, 2, 3/);assert.match(notes,/スマホ実機と音/);assert.match(notes,/Merged release PR/);for(const bad of [{...s.states[0]},{...s.states.at(-1),sha:other}])assert.throws(()=>releaseNotes(s.context,'generated',bad));
 const dir=await mkdtemp(join(tmpdir(),'silverball-notes-'));t.after(()=>rm(dir,{recursive:true,force:true}));await writeFile(join(dir,'candidate.md'),candidateNotes);await writeFile(join(dir,'published-fixture.md'),notes);});
test('attachment failure leaves a draft; retry can complete attachments before publication',async()=>{const s=setup();await executeCD(s.context,s.deps);const record=s.states.at(-1),notes=releaseNotes(s.context,'Generated',record),calls=[];let existing=null;
 const api=async(path,options={})=>{calls.push({path,options});if(path.includes('/git/ref/tags/'))return existing?{object:{type:'commit',sha}}:null;if(path.endsWith('/releases/tags/'+version))return existing;if(options.method==='POST'&&path.endsWith('/releases')){existing={id:7,tag_name:version,draft:true,body:notes,assets:[],upload_url:'https://uploads.github.com/repos/'+repo+'/releases/7/assets{?name,label}'};return existing;}if(options.method==='PATCH'){existing={...existing,...options.body,html_url:'https://example/release'};return existing;}return null;};
 await assert.rejects(publishGitHubRelease(api,s.context,notes,candidate,record,{token:'fixture',fetcher:async()=>({ok:false,status:500})}));assert.equal(existing.draft,true);assert.ok(!calls.some(c=>c.options.body?.draft===false));
 const result=await publishGitHubRelease(api,s.context,notes,candidate,record,{token:'fixture',fetcher:async()=>({ok:true,status:201})});assert.equal(result,'https://example/release');assert.equal(existing.draft,false);
});
test('workflow documents have pinned actions, no PR credentials, gated merge SHA and serial CD',async()=>{const ci=JSON.parse(await readFile(new URL('../../.github/workflows/pr-ci.yml',import.meta.url))),cd=JSON.parse(await readFile(new URL('../../.github/workflows/release-cd.yml',import.meta.url)));assert.deepEqual(ci.permissions,{contents:'read'});assert.ok(!JSON.stringify(ci).includes('secrets.'));assert.ok(!ci.on.push&&!cd.on.push&&!cd.on.pull_request_target);assert.deepEqual(cd.on.pull_request.types,['closed']);assert.equal(cd.concurrency.group,'production-cloudflare');assert.equal(cd.concurrency.queue,undefined);assert.equal(cd.concurrency['cancel-in-progress'],false);assert.match(cd.jobs.release.if,/ENABLE_PRODUCTION_CD/);assert.match(cd.jobs.release.if,/merged == true/);assert.match(cd.jobs.release.if,/head.repo.full_name == github.repository/);assert.equal(cd.jobs.release.steps[0].with.ref,'${{ github.event.pull_request.merge_commit_sha }}');assert.equal(cd.jobs.release.environment,'production');for(const w of [ci,cd])for(const step of Object.values(w.jobs)[0].steps)if(step.uses)assert.match(step.uses,/@[a-f0-9]{40}$/);});

test('historical successful rerun does not redeploy when main advanced',async()=>{const s=setup();await executeCD(s.context,s.deps);const i=inputs();i.mainSHA=other;i.tagSHA=sha;i.latestRelease={tag_name:'0.2.0'};i.release={tag_name:version,draft:false,body:'<!-- silverball-release:'+JSON.stringify(s.states.at(-1))+' -->'};assert.equal(validateCD(i).alreadyReleased,true);i.release.draft=true;assert.throws(()=>validateCD(i));});
test('failed deploy retains fresh rollback snapshot and only retries unchanged prior traffic',async()=>{const first=setup();first.deps.deploy=async()=>{throw new Error('deploy failed');};await assert.rejects(executeCD(first.context,first.deps));assert.equal(first.states[0].status,'pre-deploy');assert.ok(first.states[0].previousDeployment);const retry=setup();retry.deps.checkpoint=first.states[0];await executeCD(retry.context,retry.deps);assert.ok(retry.calls.includes('deploy'));const changed=setup();changed.deps.checkpoint=first.states[0];changed.deps.getCurrentDeployment=async()=>({id:'changed'});await assert.rejects(executeCD(changed.context,changed.deps),/reconcile/);assert.ok(!changed.calls.includes('deploy'));});
