import test from 'node:test';import assert from 'node:assert/strict';
import {SessionGame} from '../src/pixi/session-game.js';
import {createBoardFlow} from '../src/pixi/board-flow.js';
import {attachNormalSpin} from '../src/pixi/normal-spin-flow.js';
function session(rng=()=>.9){const game=new SessionGame(rng),model=createBoardFlow({lcd:true,fire:()=>game.fire()}),spin=attachNormalSpin(model.flow,{sessionGame:game,roundModel:model,lifecycle:true});return {game,model,spin};}
test('real launches debit stock and ordinary admissions pay once and queue once',()=>{const {game,model}=session();model.flow.start();for(let i=0;i<1200;i++)model.flow.step(1/120);assert.equal(game.accounting.spent,model.flow.physics.metrics.spawned);const before=game.stock,serial=game.drawSerial;model.flow.game.hit({id:9000,hits:0,x:208,y:474},'start',0);assert.equal(game.stock,before+1);assert.equal(game.drawSerial,serial+1);assert.equal(game.accounting.reconciled,true);});
test('session uses supplied production draw RNG, not review loss RNG',()=>{const {game}=session(()=>0);game.hit({id:'production-rng',hits:0},'start');const draw=game.w.active.tokuzu1;assert.equal(draw.roll,0);assert.equal(game.w.resolveDraw('tokuzu1').outcome,'symbol');});
test('pause freezes both clocks and stop-fire drains existing balls',()=>{const {game,model}=session();model.flow.start();for(let i=0;i<240;i++)model.flow.step(1/120);model.flow.pause(true);const time=game.time,physical=model.flow.physics.time;model.flow.step(.05);assert.equal(game.time,time);assert.equal(model.flow.physics.time,physical);model.flow.pause(false);model.flow.stop();const spent=game.accounting.spent;for(let i=0;i<2400;i++)model.flow.step(1/120);assert.equal(game.accounting.spent,spent);assert.ok(game.time>time);assert.equal(game.accounting.reconciled,true);});
test('unsettled progression is not silently restored and in-flight last balls are preserved',()=>{const g=new SessionGame();g.award(1000);g.checkStage();assert.equal(g.phase,'playing');assert.equal(g.stage,1);assert.equal(g.ticketEstimate,0);g.setStock(0);g.pendingBalls=1;g.tick(4);assert.equal(g.phase,'playing');g.pendingBalls=0;g.tick(4);assert.equal(g.phase,'result');});
