#if UNITY_EDITOR
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEditor;
using Yozora;
public class RuntimeStructureProbe:MonoBehaviour {
 string output;YozoraMachine m;readonly List<string> results=new List<string>();int failures;string phase="initial";readonly List<string> trace=new List<string>{"time,phase,ball,x,y,z,guided,bonusCount,fairReceived,scored"};int closedIntrusions;bool checkingClosed;
 void FixedUpdate(){if(m==null)return;foreach(var b in Object.FindObjectsByType<BallBody>(FindObjectsSortMode.None)){var p=b.transform.position;trace.Add(System.FormattableString.Invariant($"{Time.fixedTime:F5},{phase},{b.GetInstanceID()},{p.x:F6},{p.y:F6},{p.z:F6},{(b.GetComponent<FairGuidedBall>()?1:0)},{m.Rules.BonusCount},{m.FairReceived},{m.ScoredBalls}"));}if(!checkingClosed)return;foreach(var s in m.GetComponentsInChildren<PocketSensor>()){if(s.kind!=PocketKind.Attacker)continue;var c=s.GetComponent<Collider>();foreach(var b in Object.FindObjectsByType<BallBody>(FindObjectsSortMode.None))if(Vector3.Distance(c.ClosestPoint(b.transform.position),b.transform.position)<.0054f)closedIntrusions++;}}
 IEnumerator Start(){
  output=Path.GetFullPath(Path.Combine(Application.dataPath,"../../prototype/reference-review/yozora/structure-review-2026-09-26"));Directory.CreateDirectory(output);m=Object.FindFirstObjectByType<YozoraMachine>();m.GetComponent<CabinetStructureView>().SetStructureOnly(true);
  yield return null;phase="right-open";m.Command("demo-bonus");if(m.AutoFire)m.Command("fire");yield return new WaitForSeconds(1);int before=m.Rules.BonusCount;Spawn(new Vector3(.22f,.819f,-.052f));
  for(int i=0;i<20;i++){yield return new WaitForSeconds(.2f);Capture("runtime-open-"+i.ToString("D2"),new Vector3(.20f,.6f,-.9f),new Vector3(.20f,.55f,-.052f));}
  Check(m.Rules.BonusCount==before+1,"open gate accepts exactly one real moving ball",m.Rules.BonusCount-before);ClearBalls();m.ResetMachine();yield return new WaitForSeconds(.3f);phase="right-closed";checkingClosed=true;Spawn(new Vector3(.22f,.819f,-.052f));yield return new WaitForSeconds(3);Capture("runtime-closed",new Vector3(.2f,.6f,-.9f),new Vector3(.2f,.55f,-.052f));checkingClosed=false;Check(closedIntrusions==0,"closed gate physically blocks attacker sensor",closedIntrusions);Check(m.Rules.BonusCount==0&&m.Rules.Payout==0,"closed normal gate cannot award",m.Rules.Payout);ClearBalls();m.ResetMachine();
  phase="fair-five-arrivals";var selector=Object.FindFirstObjectByType<FairDistributor>();for(int i=0;i<5;i++){Spawn(selector.transform.position+Vector3.up*.008f);yield return new WaitForSeconds(.45f);}
  for(int i=0;i<30;i++){yield return new WaitForSeconds(.2f);Capture("runtime-fair-"+i.ToString("D2"),new Vector3(-.055f,.47f,-.9f),new Vector3(-.055f,.43f,-.08f));}
  Check(m.DistributorCount==5,"five physical selector arrivals",m.DistributorCount);Check(m.FairReceived==1,"selected fifth ball reaches moving rotor pocket",m.FairReceived);
  m.Command("pause");var rotor=Object.FindFirstObjectByType<RotorDrive>();var q=rotor.transform.rotation;var gate=m.GetComponent<RightMechanismDrive>().slidingGate.position;yield return new WaitForSecondsRealtime(.5f);Check(Quaternion.Angle(q,rotor.transform.rotation)<.01f&&Vector3.Distance(gate,m.GetComponent<RightMechanismDrive>().slidingGate.position)<.00001f,"pause freezes mechanism transforms",0);
  m.Command("pause");ClearBalls();m.Command("demo-bonus");if(m.AutoFire)m.Command("fire");yield return new WaitForFixedUpdate();yield return new WaitForFixedUpdate();var drive=m.GetComponent<RightMechanismDrive>();var mid=drive.slidingGate.position;m.Command("pause");yield return new WaitForSecondsRealtime(.25f);Check(Vector3.Distance(mid,drive.slidingGate.position)<.00001f,"pause during gate opening keeps its position",0);m.Command("pause");yield return new WaitForSeconds(.5f);Check(Vector3.Distance(mid,drive.slidingGate.position)>.001f,"resume completes gate travel",0);
  foreach(int rate in new[]{4,8}){ClearBalls();m.Command("demo-bonus");if(m.AutoFire)m.Command("fire");m.Command("preview-rate:"+rate);phase="right-rate-"+rate;yield return new WaitForSeconds(.5f);Spawn(new Vector3(.22f,.819f,-.052f));yield return new WaitForSeconds(4);Check(m.Rules.BonusCount==1,"right admission once at preview rate "+rate,m.Rules.BonusCount);}
  ClearBalls();m.ResetMachine();phase="normal-autofire";m.Command("fire");for(int i=0;i<10;i++){yield return new WaitForSeconds(.8f);Capture("runtime-normal-"+i.ToString("D2"),new Vector3(0,.59f,-1.72f),new Vector3(0,.565f,0));}m.Command("fire");yield return new WaitForSeconds(4);Check(m.Rules.Shots>=10&&m.DistributorCount>=5&&m.FairReceived>=1,"actual normal launcher reaches selector and rotor",m.FairReceived);
  ClearBalls();m.Command("demo-bonus");phase="bonus-autofire";for(int i=0;i<10;i++){yield return new WaitForSeconds(.8f);Capture("runtime-bonus-"+i.ToString("D2"),new Vector3(.2f,.6f,-.9f),new Vector3(.2f,.55f,-.052f));}if(m.AutoFire)m.Command("fire");Check(m.Rules.Shots>=10&&m.Rules.BonusCount>=5&&m.Rules.Payout>0,"actual bonus launcher reaches scoring aperture",m.Rules.BonusCount);
  File.WriteAllLines(Path.Combine(output,"runtime-trace.csv"),trace);File.WriteAllLines(Path.Combine(output,"runtime-results.txt"),results);Debug.Log("STRUCTURE_RUNTIME_"+(failures==0?"PASS":"FAIL")+" failures="+failures);EditorApplication.Exit(failures==0?0:1);
 }
 void Spawn(Vector3 p){var g=Object.Instantiate(m.ballPrefab,p,Quaternion.identity);g.SetActive(true);g.GetComponent<BallBody>().owner=m;g.GetComponent<Rigidbody>().linearVelocity=Vector3.down*.2f;}
 void ClearBalls(){foreach(var b in Object.FindObjectsByType<BallBody>(FindObjectsSortMode.None))Object.Destroy(b.gameObject);}
 void Check(bool ok,string name,int value){results.Add((ok?"PASS ":"FAIL ")+name+" actual="+value);if(!ok)failures++;Debug.Log(results[results.Count-1]);}
 void Capture(string name,Vector3 pos,Vector3 target){var c=m.viewCamera;var savedPos=c.transform.position;var savedRot=c.transform.rotation;float savedFov=c.fieldOfView,savedAspect=c.aspect;c.transform.position=pos;c.transform.LookAt(target);c.fieldOfView=38;c.aspect=.65f;var rt=new RenderTexture(780,1200,24);rt.Create();c.targetTexture=rt;c.Render();var old=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(780,1200,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,780,1200),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(output,name+".png"),tex.EncodeToPNG());RenderTexture.active=old;c.targetTexture=null;rt.Release();Destroy(rt);Destroy(tex);c.transform.SetPositionAndRotation(savedPos,savedRot);c.fieldOfView=savedFov;c.aspect=savedAspect;}
}

#endif
