import {spawn} from 'node:child_process';import {chromium} from '@playwright/test';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const dir='reference-review/focus-view-2026-10-03',server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5331','--strictPort','--config','reference-review/tokyoghoul-w-live/vite-record.config.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,3000));let browser;const results=[];
try{browser=await chromium.launch({channel:'chrome',headless:true});
for(const [name,size] of [['mobile',{width:390,height:844}],['desktop',{width:1280,height:960}],['desktop-short',{width:1280,height:720}],['safe-area',{width:390,height:844}],['small',{width:320,height:568}],['landscape',{width:844,height:390}]]){
const ctx=await browser.newContext({viewport:size,...(name==='mobile'?{recordVideo:{dir,size}}:{})}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));
await p.goto('http://127.0.0.1:5331/?review=session&scenario=left');await p.locator('[data-unit="0"]').click();await p.locator('#playMachine').click();await p.waitForFunction(()=>__session.snapshot()?.w);if(name==='safe-area')await p.evaluate(()=>{document.querySelector('.focus-view').style.setProperty('--panel-bottom','34px');document.querySelector('.focus-view').style.setProperty('--controls-top','107px');});await p.evaluate(()=>{__sessionReview.game().w.rng=()=>.9;});await p.waitForTimeout(1200);
const geometry=()=>p.evaluate(()=>{const c=document.querySelector('#canvas canvas').getBoundingClientRect(),r=document.querySelector('#play-controls').getBoundingClientRect(),t=document.querySelector('#controls-toggle').getBoundingClientRect();return {canvas:{x:c.x,y:c.y,right:c.right,bottom:c.bottom,width:c.width,height:c.height},panel:{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height},toggle:{x:t.x,y:t.y,right:t.right,bottom:t.bottom,height:t.height},panelHidden:document.querySelector('#play-controls').hidden,scrollWidth:document.documentElement.scrollWidth};});
const closed=await geometry();assert.equal(closed.panelHidden,true);assert.ok(closed.toggle.x>=0&&closed.toggle.right<=size.width&&closed.toggle.y>=0&&closed.toggle.bottom<=size.height&&closed.toggle.height>=44);assert.equal(await p.locator('#controls-toggle').getAttribute('aria-expanded'),'false');assert.ok(closed.canvas.x>=-.1&&closed.canvas.right<=size.width+.1&&closed.canvas.y>=-.1&&closed.canvas.bottom<=size.height+.1);await p.screenshot({path:`${dir}/${name}-closed.png`});
const before=await p.evaluate(()=>({s:__session.snapshot(),feed:__sessionReview.model().flow.continuous}));await p.locator('#controls-toggle').click();await p.waitForTimeout(900);const open=await geometry(),after=await p.evaluate(()=>({s:__session.snapshot(),feed:__sessionReview.model().flow.continuous}));assert.equal(open.panelHidden,false);assert.ok(open.toggle.x>=0&&open.toggle.right<=size.width&&open.toggle.y>=0&&open.toggle.bottom<=size.height);assert.equal(after.s.paused,false);assert.equal(after.feed,before.feed);assert.ok(after.s.time>before.s.time);assert.ok(open.canvas.x>=-.1&&open.canvas.right<=size.width+.1&&open.canvas.y>=-.1&&open.canvas.bottom<=size.height+.1);assert.ok(open.canvas.right<=open.panel.x+.1||open.canvas.bottom<=open.panel.y+.1);await p.screenshot({path:`${dir}/${name}-open.png`});
await p.locator('#feed-toggle').click();assert.equal(await p.evaluate(()=>__sessionReview.model().flow.continuous),false);await p.locator('#feed-toggle').click();assert.equal(await p.evaluate(()=>__sessionReview.model().flow.continuous),true);
await p.locator('#power-control').fill('0.26');assert.equal(await p.locator('#power-label').textContent(),'0.26');await p.locator('#menu').click();const frozen=await p.evaluate(()=>__session.snapshot());await p.waitForTimeout(500);assert.deepEqual(await p.evaluate(()=>__session.snapshot()),frozen);await p.locator('#resume').click();await p.locator('#controls-toggle').click();assert.equal(await p.locator('#controls-toggle').getAttribute('aria-expanded'),'false');assert.equal(await p.evaluate(()=>document.activeElement.id),'controls-toggle');await p.waitForTimeout(600);assert.equal(await p.evaluate(()=>__session.snapshot().paused),false);
await p.locator('#controls-toggle').click();await p.locator('#menu').click();await p.locator('#leave').click();await p.locator('#floor').click();await p.locator('[data-unit="0"]').click();await p.locator('#playMachine').click();await p.waitForFunction(()=>__session.snapshot()?.w);assert.equal(await p.locator('#controls-toggle').getAttribute('aria-expanded'),'false');assert.equal(await p.evaluate(()=>__session.snapshot().session.total),0);assert.deepEqual(errors,[]);await ctx.close();const video=name==='mobile'?await p.video().path():null;results.push({name,size,closed,open,errors,video,checks:['closed by default','toggle preserves advancing game and feeding','full canvas in viewport','open panel does not cover canvas','fire stop/start','power accessible','menu freezes/resumes','close returns focus','fresh play resets panel/totals']});
}await writeFile(`${dir}/focus-check.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results.map(r=>({name:r.name,errors:r.errors,video:r.video}))));}finally{await browser?.close();server.kill();}
