import {chromium} from '@playwright/test';
import {mkdir,writeFile,readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const base=process.env.REVIEW_URL;if(!base)throw new Error('Set REVIEW_URL to the local Vite development server');
const localURL=new URL(base);if(localURL.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(localURL.hostname))throw new Error('REVIEW_URL must be a local HTTP development server');
const out=process.env.SOUND07_DIR;if(!out)throw new Error('Set SOUND07_DIR to the private evidence directory');await mkdir(out,{recursive:true});
// Reuse the eight authored descriptors from tests/original-se.browser.mjs.
// These are isolated presentation recordings, not natural odds or accounting tests.
const fixtures=[
 ['pressure-loss',{variant:'pressure',win:false},54],
 ['initiative-win',{variant:'initiative',win:true},54],
 ['exchange-loss',{variant:'exchange',win:false},54],
 ['pressure-revival',{variant:'pressure',win:true,ending:'revival'},58],
 ['rush-flash',{variant:'pressure',win:true,ending:'flash',mode:'rush'},12],
 ['basic-loss',{route:'basic',win:false},7],
 ['direct-win',{route:'direct',win:true},4],
 ['moon-fullrotation',{variant:'pressure',win:true,premium:'moon',full:true},54]
];
const sourceFiles=['prototype/src/pixi/se/original-se.js','prototype/src/pixi/se/synth-wave.js','prototype/src/pixi/se/presentation-sound.js','prototype/src/pixi/se/presentation-atmosphere.js','prototype/src/pixi/se/presentation-cues.js'];
const toolSHA=createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex');const source={};for(const file of sourceFiles)source[file]=createHash('sha256').update(await readFile(file)).digest('hex');
const runtimeInputs=[];async function inventory(dir){for(const item of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){const path=dir+'/'+item.name;if(item.isDirectory())await inventory(path);else if(item.isFile()){const bytes=await readFile(path);runtimeInputs.push({path,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}}}for(const dir of ['prototype/src','prototype/public'])await inventory(dir);const runtimeAssetSHA=createHash('sha256').update(JSON.stringify(runtimeInputs)).digest('hex');const selected=process.env.SOUND07_CASES?.split(',')??null;const browser=await chromium.launch({channel:'chrome',headless:true});const runs=[],errors=[];
async function setup(){const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/?review=session&scenario=predictions');await page.locator('[data-kind=main]').first().click();await page.locator('#playMachine').click();await page.waitForFunction(()=>!!window.__sessionReview?.board?.(),null,{timeout:60000});await page.locator('#intro-skip').click();await page.locator('#feed-toggle').click();await page.locator('[data-view=lcd]').click();await page.waitForFunction(()=>__sessionReview.board().audio().state==='running');return page;}
async function record(page,name,fixture){
 await page.evaluate(async f=>{
 const board=__sessionReview.board(),g=__sessionReview.game();board.setSound(true);
 if(f){g.presentation={id:100,drawId:100,time:0,basicReach:true,longReach:!f.route,displayRoute:f.route??(f.ending==='flash'?'flash':'battle'),presentationMode:f.mode??'normal',reachVariant:f.variant,reachEnding:f.ending??'standard',win:f.win,premium:f.premium,premiumAt:45.5,predictionPlan:f.full?{resultFamily:'fullrotation',chanceUps:[],precursorSeconds:0}:null};delete g.previewWinAt;g.spinActive=false;g.jackpot=null;}
 window.sound07Origin=performance.now();window.sound07Inputs=[{wallMs:0,action:f?'authored fixture start':'normal review start',presentationTime:g.presentation?.time??null}];window.sound07Chunks=[];window.sound07Audio=board;
 const canvas=board.canvas,stream=new MediaStream([...canvas.captureStream(30).getVideoTracks(),...board.audioStream().getAudioTracks()]);window.sound07Stream=stream;
 const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')?'video/webm;codecs=vp8,opus':'video/webm';const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1500000});recorder.ondataavailable=e=>sound07Chunks.push(e.data);recorder.start();window.sound07Recorder=recorder;
 },fixture??null);
 await page.screenshot({path:out+'/'+name+'-start.png'});
}
async function mark(page,action){return page.evaluate(action=>{const g=__sessionReview.game();const value={wallMs:Math.round(performance.now()-sound07Origin),action,presentationTime:g?.presentation?.time??null,gameTime:g?.time??null,audio:__sessionReview.board()?.audio()};sound07Inputs.push(value);return value;},action);}
async function finish(page,name,fixture,scope){
 await page.screenshot({path:out+'/'+name+'-end.png'});
 const data=await page.evaluate(async()=>{const rec=sound07Recorder;await new Promise(resolve=>{rec.onstop=resolve;rec.stop();});const bytes=Array.from(new Uint8Array(await new Blob(sound07Chunks,{type:rec.mimeType}).arrayBuffer()));for(const track of sound07Stream.getTracks())track.stop();return {bytes,mime:rec.mimeType,wallMs:Math.round(performance.now()-sound07Origin),inputs:sound07Inputs,audio:sound07Audio.audio(),snapshot:__sessionReview.board()?.snapshot()};});
 if(data.bytes.length<1000)throw new Error('Recording is empty: '+name);
 await writeFile(out+'/'+name+'.webm',Buffer.from(data.bytes));delete data.bytes;const cues=fixture?await page.evaluate(async f=>{const {reachAudioCues}=await import('/src/pixi/se/presentation-cues.js');return reachAudioCues({longReach:!f.route,displayRoute:f.route??(f.ending==='flash'?'flash':'battle'),presentationMode:f.mode??'normal',reachVariant:f.variant,reachEnding:f.ending??'standard',win:f.win,premium:f.premium,premiumAt:45.5,predictionPlan:f.full?{resultFamily:'fullrotation',chanceUps:[],precursorSeconds:0}:null});},fixture):[];
 const result={name,fixture:fixture??null,scope,cues,...data,listening:'unverified',input:'mouse, isolated authored presentation',clock:'full-speed continuous; no seek',audioCapture:'real AudioContext MediaRecorder, not proof of auditory quality',captureScope:'Canvas video only; DOM PUSH and controls are absent from video, supplemented by PNG and timestamped input JSON'};await writeFile(out+'/'+name+'.json',JSON.stringify(result,null,2));runs.push(result);console.log('Recorded '+name+'; listening remains unverified');
}
try{
 for(const [name,fixture,seconds] of [['normal',null,18],...fixtures,...(selected?.includes('normal-admission')?[['normal-admission',null,90]]:[])].filter(row=>!selected||selected.includes(row[0]))){const page=await setup();await record(page,name,fixture);if(name==='normal-admission'){await page.locator('#feed-toggle').click();await mark(page,'normal launch started');await page.waitForFunction(()=>__sessionReview.board().snapshot().spin.accepted>0&&__sessionReview.board().snapshot().spin.draws>0,null,{timeout:90000});await page.locator('#feed-toggle').click();await mark(page,'normal entry/initial consumption observed, launch stopped');}else if(fixture)await page.waitForFunction(()=>!__sessionReview.game().presentation,null,{timeout:(seconds+30)*1000});else await page.waitForTimeout(seconds*1000);await page.waitForTimeout(1500);await mark(page,'continuous interval finished');await finish(page,name,fixture,fixture?'one of the existing eight authored fixtures, continuous nominal full duration':name==='normal-admission'?'normal physical admission/initial consumption in a review session; not a natural odds calibration':'normal idle review; not a natural-entry calibration');await page.context().close();}
 if(!selected||selected.includes('operations')){const page=await setup();const fixture=fixtures[0][1];await record(page,'operations',fixture);await page.waitForTimeout(2500);await page.locator('#controls-toggle').click();const sound=page.locator('#sound-enabled');await sound.scrollIntoViewIfNeeded();await sound.uncheck();await mark(page,'sound off (checkbox unchecked)');await page.screenshot({path:out+'/operations-sound-off.png'});await page.waitForTimeout(700);await sound.check();await mark(page,'sound on (checkbox checked)');await page.locator('#controls-toggle').click();await page.locator('#quick-pause').click();await mark(page,'pause');await page.screenshot({path:out+'/operations-paused.png'});await page.waitForTimeout(700);await page.locator('#resume').click();await mark(page,'resume');
 const other=await page.context().newPage();await other.goto('about:blank');await other.bringToFront();let hidden=false;try{await page.waitForFunction(()=>document.hidden,null,{timeout:1500});hidden=true;}catch{}await mark(page,hidden?'visibility hidden':'visibility hidden unavailable in this headless environment');await page.bringToFront();await other.close();if(await page.locator('#resume').isVisible())await page.locator('#resume').click();await mark(page,'visibility return');await page.locator('.decision-push-button').waitFor({state:'visible',timeout:70000});await mark(page,'PUSH visible, before click');await page.screenshot({path:out+'/operations-push.png'});await page.locator('.decision-push-button').click();await mark(page,'PUSH clicked');await page.waitForFunction(()=>!__sessionReview.game().presentation,null,{timeout:15000});await page.waitForTimeout(1500);await finish(page,'operations',fixture,'interrupted controls and actual PUSH sample; not full uninterrupted listening');
 const board=await page.evaluateHandle(()=>__sessionReview.board());await page.locator('#quick-pause').click();await page.locator('#leave').click();await page.locator('#floor').click();await page.waitForTimeout(200);await page.screenshot({path:out+'/operations-cleanup.png'});const cleanup=await board.evaluate(b=>({audio:b.audio(),canvasCount:document.querySelectorAll('#canvas canvas').length}));await writeFile(out+'/cleanup.json',JSON.stringify({cleanup,listening:'unverified'},null,2));await page.context().close();}
 for(const name of ['normal',...fixtures.map(x=>x[0]),'normal-admission','operations'])if(!runs.some(r=>r.name===name)){try{runs.push(JSON.parse(await readFile(out+'/'+name+'.json','utf8')));}catch{}}
 await writeFile(out+'/index.json',JSON.stringify({date:new Date().toISOString(),gitSHA:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),source,runtimeAssetSHA,runtimeInputs,toolSHA,base,viewport:'390x844',browser:await browser.version(),runs:runs.map(r=>({name:r.name,scope:r.scope,wallMs:r.wallMs,listening:r.listening})),errors,status:'recording-prepared, listening unverified'},null,2));if(errors.length)throw Error('Browser errors: '+errors.join('; '));
 const wav=process.env.SOUND07_WAV==='1';if(wav){execFileSync('ffmpeg',['-version'],{stdio:'ignore'});for(const r of runs)execFileSync('ffmpeg',['-nostdin','-v','error','-y','-i',out+'/'+r.name+'.webm','-map','0:a:0','-c:a','pcm_f32le',out+'/'+r.name+'.wav']);}
 const escape=text=>String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
 const sections=runs.map(r=>'<section><h2>'+escape(r.name)+'</h2><p>録音素材・聴感未評価。'+escape(r.scope)+'</p><video width=320 controls preload=none src="'+r.name+'.webm"></video>'+(wav?'<p>同じ録音から無加工で復号したWAV（原合成PCMとのbit一致ではありません）</p><audio controls preload=none src="'+r.name+'.wav"></audio>':'')+'<p><a href="'+r.name+'.json">時刻・入力・cue記録</a> / <a href="'+r.name+'-start.png">開始画面</a> / <a href="'+r.name+'-end.png">終了画面</a></p><ul>'+r.inputs.map(i=>'<li>'+Math.round(i.wallMs/100)/10+'秒：'+escape(i.action)+'</li>').join('')+'</ul></section>').join('');
 await writeFile(out+'/index.html','<!doctype html><html lang=ja><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>S2 #7 ローカル試聴素材</title><style>body{font:16px system-ui;max-width:900px;margin:24px auto;padding:0 16px;background:#f3f4f6;color:#172033}section{background:white;margin:20px 0;padding:20px}video,audio{max-width:100%}a{color:#1657a8}table{border-collapse:collapse}td,th{padding:8px;border:1px solid #aaa}</style><h1>S2 #7 ローカル試聴素材</h1><p>録音成功と、人が聴いて評価した結果は別です。全素材は現在「未聴取・未評価」。外部公開していません。</p><p>動画はcanvasのみ。DOMのPUSH・操作UIは動画に含まれません。<a href="operations-push.png">PUSH画面</a> / <a href="operations-sound-off.png">音off画面</a> / <a href="operations-paused.png">休止画面</a> と時刻JSONで補助します。</p><table><tr><th>記録する環境</th><td>聴く人 / PC・ブラウザ / 出力機器 / 音量</td></tr><tr><th>評価軸</th><td>役割・映像との同期・バランス・連続性・当落秘匿・操作復帰</td></tr><tr><th>残す結果</th><td>素材名 / 録画内秒 / 聴こえた事実 / 合格・要改善・未検証</td></tr></table>'+sections+'</html>');
}catch(error){await writeFile(out+'/partial-index.json',JSON.stringify({date:new Date().toISOString(),source,runtimeAssetSHA,toolSHA,base,runs:runs.map(r=>({name:r.name,scope:r.scope,wallMs:r.wallMs,listening:r.listening})),errors,error:String(error),status:'incomplete; listening unverified'},null,2));throw error;}finally{await browser.close();}
