import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {makePins} from '../../src/physics.js';
const dir='reference-review/pixi-pins';await mkdir(`${dir}/video`,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
try{const context=await browser.newContext({viewport:{width:1040,height:940},deviceScaleFactor:1,recordVideo:{dir:`${dir}/video`,size:{width:1040,height:940}}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://localhost:5173/pins-pixi.html');await page.waitForFunction(()=>!!window.__pins);await page.locator('#demo').click();const states=[];
for(let i=0;i<3;i++){await page.waitForFunction(t=>window.__pins.snapshot().time>t,8+i*12,{timeout:25000});const s=await page.evaluate(()=>window.__pins.snapshot());assert.equal(s.zone,i);assert.deepEqual(s.pins,makePins());assert.ok(s.displayed.length>=3);for(const p of s.displayed){const original=s.pins.find(q=>q.id===p.id);assert.equal(p.x,Math.round((original.x-s.origin.x)*s.scale));assert.equal(p.y,Math.round((original.y-s.origin.y)*s.scale));assert.equal(p.r,original.r);}assert.ok(s.roleFlow[['spread','yori','michi'][i]].balls>0);states.push(s);await page.screenshot({path:`${dir}/${['spread','yori','michi'][i]}.png`});}
await page.waitForFunction(()=>window.__pins.snapshot().time>40,{},{timeout:20000});await page.locator('#pause').click();const paused=await page.evaluate(()=>window.__pins.snapshot());await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>window.__pins.snapshot()),paused);await page.locator('#guides').check();await page.screenshot({path:`${dir}/alignment.png`});
const asset=await page.evaluate(()=>window.__pins.asset());await writeFile(`${dir}/pin.png`,Buffer.from(asset.split(',')[1],'base64'));assert.deepEqual(errors,[]);await writeFile(`${dir}/verification.json`,JSON.stringify({states,paused,errors},null,2));const video=page.video();await context.close();await video.saveAs(`${dir}/pins-demo.webm`);console.log(JSON.stringify({states:states.map(s=>({zone:s.zone,spawned:s.spawned,pins:s.displayed.length})),errors}));}finally{await browser.close();}
